### ISSUE TITLE
Publish on Spark Packages Main Repository

### ISSUE THREAD

**Issue by brkyvz** [sramirez/spark-infotheoretic-feature-selection#1]
Hi @sramirez,

Would you like to make a release of this package on the Spark Packages Maven Repo **as well**? There is an sbt-plugin called [sbt-spark-package](https://github.com/databricks/sbt-spark-package) that would help you make the release straight from your sbt console. All you need to do is set a couple configurations.

Publishing on the Spark Packages Repo will bump your ranking on the website, and will fill in the How To section, which users can use to include your package in their work.

Please let me know if you have any comments/questions/suggestions!

Best,
Burak

P.S. I bolded **as well** so that you would at least know that this is not an automatically generated message :)

**Comment by sparadiso** [comment]
+1 would appreciate maven support.

**Comment by sramirez** [comment]
Hi, I think it is solved because I uploaded the software to the Spark packages web long time ago:

https://spark-packages.org/package/sramirez/spark-infotheoretic-feature-selection

It is ok for you?
Is it ok for you?
