### ISSUE TITLE
How I can extract output Features with Scores from InfoThSelector ?

### ISSUE THREAD

**Issue by mkhalid12** [sramirez/spark-infotheoretic-feature-selection#13]
I am using MIM feature selector model. It running perfectly fine and output the features results automatically in a terminal. How can I extract output features with its relevant score? I want to save this output to a file.
```
val selector = new InfoThSelector()
         .setSelectCriterion("mim")
         .setNumTopFeatures(2)
         .setFeaturesCol("features")
         .setLabelCol("class")
         .setOutputCol("selectedFeatures")
```

**Comment by sramirez** [comment]
Scores are printed as standard output as far as I remember. You may extract them from your Spark logs. You can also modify the code to generate your output as demanded.
