### ISSUE TITLE
Could you deploy a sources jar to maven along with the executable jar?

### ISSUE THREAD

**Issue by jconwell** [sramirez/spark-infotheoretic-feature-selection#14]
Would it be possible to build and deploy a sources jar along with the execution jar when you deploy to the maven repository?  Having the source makes it easy to debug and follow the code during execution.

Its pretty easy, just add the sources plugin section (link below) to the pom file and it'll create the sources jar when you run package. 

https://maven.apache.org/plugin-developers/cookbook/attach-source-javadoc-artifacts.html

**Comment by sramirez** [comment]
Please, create a PR with the changes, and I will accept it ASAP.
