### ISSUE TITLE
Failing to build on sbt

### ISSUE THREAD

**Issue by saifellafi** [sramirez/spark-infotheoretic-feature-selection#2]
/path/to/spark-infotheoretic-feature-selection/build.sbt:19: error: not found: value sparkPackageName
sparkPackageName := "sramirez/infotheoretic-feature-selection"
^
[error] Type error in expression

---

All I did change was sparkVersion and libraryDependencies to 1.4.0

Thanks

**Comment by saifellafi** [comment]
Also tried to change sparkPackageName to spName with no effect.

**Comment by saifellafi** [comment]
Fixed it. To fix it change in project/build.properties:

sbt.version=0.13.8

**Comment by sramirez** [comment]
Thank you very much for the help. I've always used maven to compile this project.
Anyway, you can use directly the spark package associated to this proyect in your spark enviroment.
Reference: http://spark-packages.org/package/sramirez/spark-infotheoretic-feature-selection

**Comment by saifellafi** [comment]
Sorry for my ignorance, does the --package launch mode requests mvn to resolve dependencies?

**Comment by sramirez** [comment]
No, it's a self-content package that is automatically provided by spark executables (shell or submit). Try it out and tell me if you have a problem. I'll appreciate any comment.

**Comment by saifellafi** [comment]
Thank you. But yes, it is a maven resolver. I was asking since in my framework I have maven repos blocked, so that was not an option. In any case, it is working by manual source-packaging with SBT now :-)

::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: sramirez#spark-infotheoretic-feature-selection;1.1: not found

                ::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
        Server access error at url https://repo1.maven.org/maven2/sramirez/spark-infotheoretic-feature-selection/1.1/spark-infotheoretic-feature-selection-1.1.pom (javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?)

**Comment by sramirez** [comment]
OK, for me this instruction works pretty well:

> $SPARK_HOME/bin/spark-shell --packages sramirez:spark-infotheoretic-feature-selection:1.1

You only need to activate maven repos and, of course, your network connection ;)
