### ISSUE TITLE
error for type does not take parameters

### ISSUE THREAD

**Issue by VanessaD** [sramirez/spark-infotheoretic-feature-selection#3]
Hi I'm trying the given example (mllib) but encountered the following error messages: 

  val featureSelector = InfoThSelector(criterion, nToSelect, nPartitions).fit(data)
org.apache.spark.mllib.feature.InfoThSelector.type does not take parameters
    val featureSelector = InfoThSelector(criterion, nToSelect, nPartitions).fit(data)

Any ideas? Would appreciate very much for the help. 

Wei

**Comment by sramirez** [comment]
Hi Vannesa,

I've just modified the example in the README file. You need to initialize the InfoThSelector object with new, doing that:

val featureSelector = **new** InfoThSelector(criterion, nToSelect, nPartitions).fit(data)

Sorry for the mistake

**Comment by VanessaD** [comment]
thanks for the reply. I tried it using new, but getting the following errors as well:

<img width="761" alt="screen shot 2016-07-12 at 4 57 08 pm" src="https://cloud.githubusercontent.com/assets/762209/16787521/b93066a6-4851-11e6-8b51-76c1dbcc77e9.png">


 The scala version I used is 1.4, so I am using "spark-infotheoretic-feature-selection-1.1.jar". Any help would be much appreciated.

**Comment by sramirez** [comment]
It seems that there is a problem related to the class $iwC. Do you know where this class come from?

In order to guess the origin of the problem, could you describe the whole process you carried out before getting this error, please?

Thanks

**Comment by VanessaD** [comment]
Thanks for your feedback. Here's how it went. I launched the spark-shell with the 1.1 version jar. 

spark-shell --jars spark-infotheoretic-feature-selection-1.1.jar
```
import org.apache.spark.mllib.regression.LabeledPoint
import org.apache.spark.mllib.linalg.Vectors
import org.apache.spark.mllib.util.MLUtils
import org.apache.spark.{SparkContext, rdd}
```

loaded the sample_svm data
`val data = MLUtils.loadLibSVMFile(sc, "/***/sample_libsvm_data.txt")`

data was fine, I did check then, then followed the example: 
import org.apache.spark.mllib.feature._
```
val criterion = new InfoThCriterionFactory("mrmr")
val nToSelect = 100
val nPartitions = 100
```

```
println("*** FS criterion: " + criterion.getCriterion.toString)
println("*** Number of features to select: " + nToSelect)
println("*** Number of partitions: " + nPartitions)
```

The error comes when starting this line:
`val featureSelector = new InfoThSelector(criterion, nToSelect, nPartitions).fit(data)`

<img width="1271" alt="screen shot 2016-07-27 at 11 35 09 am" src="https://cloud.githubusercontent.com/assets/762209/17187486/4186adf6-53ee-11e6-8c6f-664f75fa39f8.png">

**Comment by sramirez** [comment]
Hello again,

Sorry for the delay! I was on vacations :D 

Please, could you use the following command to import my code:

$SPARK_HOME/bin/spark-shell --packages sramirez:spark-infotheoretic-feature-selection:1.3.1

I suppose your problem is caused by some class access priveledges. By using the newest version and the maven system, I think you won't have any problem. Could you try again, please?

Thanks for your feedback!
