### ISSUE TITLE
ThCriterionFactory is not a member of package org.apache.spark.mllib.feature

### ISSUE THREAD

**Issue by ivancanfly** [sramirez/spark-infotheoretic-feature-selection#4]
Hi, I am using the spark-infotheoretic-feature-selection jar file. I import the jar file into my project and maven the project,but it occur the error as follows:
![image](https://cloud.githubusercontent.com/assets/7590346/16728507/4e8c5958-4799-11e6-94ce-c91b5f263c4f.png)

I don't know how to fix it?  May the jar file conflit with the origin mllib.feature jar file ?

Thank you

**Comment by sramirez** [comment]
Hi Ivan,

Have you imported it correctly? Maybe you haven't include it in the classpath?

Please, try to import another class from my package to know if the problem comes from this class or it affects all.
