### ISSUE TITLE
All criterion same ranking

### ISSUE THREAD

**Issue by jabenitez** [sramirez/spark-infotheoretic-feature-selection#6]
I just tried all the criterion on the same dataset. But I get  the same ranking no matter what i set the SelectCriterion to. 

![image](https://cloud.githubusercontent.com/assets/2036220/18478945/1db932d0-79a1-11e6-8a4d-166ffcee2f86.png)

I was wondering if I need to do a particular transform to my data before running the selector. 

When running, I first apply a minmaxscaler to all features then multiply by 255 round off to int and finally subtract 128 so they are the byte range.

**Comment by sramirez** [comment]
Data must be discretized to get better results, but it can work with continuous data.
InfoThCriterionFactory works well, I've tried with several criterion without problems. Have you debugged to check if the right criterion is selected or not?
