### ISSUE TITLE
Spark 2.0.0 support for feature selection and MDL

### ISSUE THREAD

**Issue by kiranvaranasi81** [sramirez/spark-infotheoretic-feature-selection#7]
Currently feature selection and MDL techniques are built using spark 1.6.1. Is there plan to support spark 2.0.0 or latest versions?.

**Comment by sramirez** [comment]
Actually, this packages has support for 2.0.0. Just take a look at the last commit. Thanks to @jabenitez you can build it on Spark 2.0.0. Concerning the MDLP discretizer, I am working on this feature now.
